version: 0.2

environment_variables:
  plaintext:
    ENVIRONMENT: "testing"
    REACT_APP_AUTH_API_URL: "https://cc-api.tst.payperform.com/v1"
    REACT_APP_BMS_SERVICE_API_URL: "https://bms-api.tst.payperform.com"
    REACT_APP_CLIENT_CONNECT_API_URL: "https://cc-api.tst.payperform.com/v1"
    REACT_APP_RATES_API_URL: "https://pc-rates.tst.payconstruct.com"
    REACT_APP_BENEFICIARY_API_URL: "https://pc-beneficiary.tst.payconstruct.com"
    REACT_APP_TRADES_API_URL: "https://pp-efx-orders.tst.payperform.com"
    REACT_APP_ROUTES_API_URL: "https://pp-efx-routes.tst.payperform.com"
    REACT_APP_FINANCE_API_URL: "https://pp-efx-finance.tst.payperform.com"
    REACT_APP_TERMS_SERVICES_DOC_URL: "https://cc-terms-service-document.tst.payperform.com/v1"
    REACT_APP_GPP_API_URL: "https://gpp-api.tst.payconstruct.com/v1"
    REACT_APP_AUTH0_CLIENT_ID: "I6WFZDevGMdl91cp2RRgU4he4oHL14Nv"
    REACT_APP_AUTH0_AUDIENCE: "https://cc-api.tst.payconstruct.com"
    REACT_APP_AUTH0_DOMAIN: "tst-client-connect.eu.auth0.com"
    REACT_APP_AUTH0_REDIRECTION_URL: "https://control.tst.payperform.com/verify-authorization"
    REACT_APP_AUTH0_SCOPE: "openid profile email address phone offline_access enroll read:authenticators remove:authenticators"
    REACT_APP_LOGOUT_URL: "https://control.tst.payperform.com/login"
    REACT_APP_PAYMENT_API_URL: "https://pay-engine.tst.getorbital.com"
    REACT_APP_PERSIST_SECRET_KEY: ${ssm:/cc/REACT_PERSIST_ENCRYPT_KEY}
    REACT_APP_UPLOAD_FILES_API_URL: "https://pay-file-manager.tst.getorbital.com/"

phases:
  install:
    commands:
      # Install nodejs https://nodejs.org/en/download/package-manager/
      - apt-get update -y
      - apt-get install ca-certificates
      #- curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - npm install -g yarn
      # Install yarn natively httpss://yarnpkg.com/en/docs/install#linux-tab
      #      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      #      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      #      - apt-get update
      - apt-get install -y python3-pip awscli s3cmd
  pre_build:
    commands:
      - aws s3 cp s3://$STAGE-npm-token/.npmrc src
      - cd src
      - ls
      #- npm install
      - yarn install
  build:
    commands:
      #      - npm run-script test
      #- npm run-script build
      - yarn build
  post_build:
    commands:
      - aws s3 cp build s3://${S3_DEPLOY_BUCKET} --recursive
#      - cd $CODEBUILD_SRC_DIR/build; zip -r ../build.zip *
#artifacts:
#  files:
#    - "**/*"
#  base-directory: "build*"
#artifacts:
#  files:
#    - build.zip
#  discard-paths: yes
#  post_build:
#    commands:
#      - aws s3 sync --delete --exclude assets/* build/ "s3://${BUCKET_NAME}"
#      - aws s3 sync --delete --cache-control "max-age=31536000" build/assets "s3://${BUCKET_NAME}/assets"
#artifacts:
#  files:
#    - */*
#  base-directory: build
